#!/bin/bash
amazon-linux-extras install -y epel
yum install -y stress
mkdir /nfs-client
mount -t nfs 172.16.2.100:/nfs-shared /nfs-client
ec2-metadata -o | cut -d ' ' -f 2 >> /nfs-client/list.txt
umount 172.16.2.100:/nfs-shared
rmdir /nfs-client
wget https://raw.githubusercontent.com/netidgo/project2/refs/heads/main/dvwa_config.sh
chmod +x dvwa_config.sh
sh dvwa_config.sh
rm -f dvwa_config.sh
availability_zone=$(ec2-metadata -z)
instance_id=$(ec2-metadata -i)
private_ip=$(ec2-metadata -o)
cat <<EOF > /var/www/html/index.html
<h1>Welcome to Homepage~!</h1>
<h3>${availability_zone}</h3>
<h3>${instance_id}</h3>
<h3>${private_ip}</h3>
<h2><a href="./login.php">DVWA Web</h2>
EOF
